#!/bin/bash

echo "🚀 初始化 EAS 專案"
echo "=================="
echo ""
echo "請選擇一個選項："
echo "1) 建立新的 EAS 專案"
echo "2) 連結到現有的 EAS 專案"
echo ""
echo "執行步驟："
echo ""
echo "選項 1 - 建立新專案："
echo "  eas init"
echo "  # 按 Y 確認覆蓋現有的 project ID"
echo ""
echo "選項 2 - 連結現有專案："
echo "  eas init --id [您的專案ID]"
echo ""
echo "完成後，執行："
echo "  eas project:info"
echo ""
echo "記錄下顯示的 Project ID，我們需要更新到配置檔案中。"